version: '3'
services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_pass_example
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - client
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=pg_pass_example
      - PGDATABASE=postgres
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CI=true
    depends_on:
      - db
      - redis
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis